### ISSUE TITLE
MinMinGuard不起作用

### ISSUE THREAD

**Issue by ShekBoy** [taichi-framework/TaiChi#28]
手机型号：Sony XZ Premium
ROM版本：Android 9.0
Xposed模块：MinMinGuard 2.0.2
APP：全部含有广告的APP

问题描述：MinMinGuard已检测到Xposed且能进行设置但没有任何去广告效果，检测不出来APP广告，广告拦截数永远是0

其他 Magisk 模块：MM管理器，太极内核3.2-a

补充：已尝试过重启，强制停止APP，改用3.2-b内核依然没有效果

**Comment by akang1937** [comment]
我今天也试过了，MinMinGuard没有任何效果，无法拦截广告，广告拦截数永远是0.

**Comment by exodius48** [comment]
@tiann MinMinGuard has been updated to 2.0.3 beta. I'm using xiaomi pocophone f1, MIUI 10, android 9. Taichi version 5.0.5-36, it does not detect on TaiChi (not compatible) . No root, locked bootloader.

**Comment by tomissmart86520** [comment]
@tiann update to 2.0.5 beta

**Comment by iaston** [comment]
希望支持

**Comment by mubkk** [comment]
Taichi 5.3.2-548 with magisk module
It can't support minminguard 2.1.1 which is latest one this moment.

**Comment by tiann** [comment]
fixed in 5.5.1

**Comment by mubkk** [comment]
sir, it seems not fixed yet.
it still show module not supported.
regards

**Comment by tiann** [comment]
try minminguard version 2.1.1

**Comment by mubkk** [comment]
Sir,

Good day.
Thank you for your reply.

I already use version 2.1.1 (download from official xposed page
https://repo.xposed.info/module/tw.fatminmin.xposed.minminguard )
and it did not work.

Regards.

***************************
 Masato Ueno
 m.ueno.th@gmail.com
***************************


2019年9月1日(日) 9:52 weishu <notifications@github.com>:

**Comment by tiann** [comment]
how did you use it?

**Comment by mubkk** [comment]
Sir,

Report.
I tried to install again.
Very strange, this time (I tried 2 more times before) I can use it now !
Thank you so much for your strong assist.

Regards.

***************************
 Masato Ueno
 m.ueno.th@gmail.com
***************************


2019年9月2日(月) 11:38 weishu <notifications@github.com>:
